
server:
  port: 9013

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

zeebe:
  client:
    broker:
      contactPoint: "zeebe-cluster-zeebe:26500"
    requestTimeout: "500ms"
    job:
      pollInterval: "1s"
      timeout: "10s"
    security:
      plaintext: true

logging:
  level:
    root: DEBUG
    io.zeebe: TRACE

